### ISSUE TITLE
Keybinds reset when Blender is loaded

### ISSUE THREAD

**Issue by alinsavix** [ThatAsherGuy/ATB#1]
With commit 600a9d1 (haven't tested with others), it appears that keybinds are reset each time Blender is loaded.

To reproduce:

1. Preferences > Add-ons > ATB
2. Keymap panel > Basic Config, disable everything except "Fast Panel" (just as an example)
3. Optionally bind Fast Panel to alt-RMB
4. Exit Blender. Start Blender
5. Go back to Preferences > Add-ons > ATB and observe that all settings are back at default

**Comment by ThatAsherGuy** [comment]
Hmm, I have a suspicion about what's causing this; I'll look into it.

Thanks for the detailed report!

**Comment by alinsavix** [comment]
Verified this is fixed in b0496b0f56542feb4600e482cb23cbfed9cd9e34
